### ISSUE TITLE
Navigation Solution version

### ISSUE THREAD

**Issue by y-lai** [stoic-roboticist/kmriiwa_ros_java#1]
Hi @stoic-roboticist ,

I'm trying to get your kmriiwa stack up and running on our KMR omnimove 200.
In the instructions for the sunrise.workbench project, there is a need to copy the relevant .jar files to access the laserscanner and the odometry. (In particular the nav.provider_*.jar and the nav.robot.fdi.api_*.jar)

Are you able to disclose which version of Sunrise.NavigationSolution you are using to gain access to those jar files in the plugins folder?
I'm currently using NavigationSolution v1.13 and am unable to find those jar files.

Cheers,
y-lai

**Comment by emielke12** [comment]
I too am running into the same issue here.

**Comment by stoic-roboticist** [comment]
Hi @y-lai and @emielke12 , 

We are also using NavigationSolution v1.13. The particular version for the mentioned files are:
1- com.kuka.nav.provider_1.0.0.300_release_release_1_13_8d78351739.jar
2- com.kuka.nav.robot.fdi.api_1.0.0.300_release_release_1_13_8d78351739.jar
We got those files from the "plugins" folder inside our SunriseWorkbench-1.16 installation directory

I hope that helps.

**Comment by emielke12** [comment]
@stoic-roboticist Yes! I thought these would already have been added to the build path, but couldn't see them. Adding them in removed the errors. Thank you!

**Comment by y-lai** [comment]
Hi @stoic-roboticist ,

Thanks a lot for that clarification and the quick response.
With our current installation with NavigationSolution v1.13, those jar files are absent in our plugins folder.
It seems like we need to troubleshoot our installation and/or chase up with KUKA on our end to double check the installer we obtained.

Cheers,
y-lai

**Comment by y-lai** [comment]
Hi @stoic-roboticist ,

Just an FYI.
It might be worthwhile amending the README in the "clone and setup the robotic application" section - step 5.
There are two installation folder locations from Sunrise Workbench in Windows: 
- One exists in \<Drive\>:\ **Program Files (x86)** \KUKA\SunriseWorkbench\plugins
- Another exists in \<Drive\>:\ **ProgramData** \KUKA\SunriseWorkbench\plugins

The jar files exist in the "ProgramData" version of the plugins folder which is hidden by default in Windows.
We were able to debug this by contacting our local KUKA office to get guidance on the absolute path of the installation folder.

Cheers,
y-lai
