### ISSUE TITLE
What does FDI refer to in KMRMsgGenerator.java?

### ISSUE THREAD

**Issue by twtoner** [stoic-roboticist/kmriiwa_ros_java#2]
First of all, many thanks for putting together such a useful package.

I am attempting to integrate the software with our Sunrise project to deploy to our KMR. We have the same version, 1.16, and the same software packages listed in the readme.

However, I continue to get compilation errors in KMRMsgGenerator.java on lines 3-5, indicating that we do not have the proper files for com.kuka.nav.fdi.* or com.kuka.nav.provider.*. In our plugins folder in our SunriseWorkbench installation, we do not have these .jar files either. 

I have searched online and on xpert.kuka.com and I cannot find any reference to these packages. Can you please indicate if these belong to a certain package that we may not have? Any help is appreciated - thanks!

**Comment by AswinkarthikeyenAK** [comment]
Hi @twtoner, 
Please check with KUKA and maybe they will be able to provide you with the jar files.

**Comment by stoic-roboticist** [comment]
Hi @AswinkarthikeyenAK 
These jar files come as part of one of the options we got with SunriseWorkbench 1.16 installation. Namely, KUKA.NavSolution 1.16 option. The specified jar files come with this package plugins. I hope this helps.

**Comment by AswinkarthikeyenAK** [comment]
Hi @stoic-roboticist 
Thank you for the information.
We have the pacakage. This information will be helpful for @twtoner .

Thank you
